[2023-07-05T13:43:35.394+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:43:35.396+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:43:35.401+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.400+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:43:35.428+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.427+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:43:35.433+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.432+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:43:35.436+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.435+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:43:35.441+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:43:35.662+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.662+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:exercise17
[2023-07-05T13:43:35.691+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.691+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:exercise17
[2023-07-05T13:43:35.708+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.707+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:exercise17
[2023-07-05T13:43:35.731+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.731+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:43:35.755+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.755+0000] {dag.py:2747} INFO - Creating ORM DAG for exercise17
[2023-07-05T13:43:35.779+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:43:35.778+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:43:35.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.424 seconds
[2023-07-05T13:44:06.106+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:06.109+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:44:06.113+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.113+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:06.131+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.130+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:44:06.134+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.133+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:44:06.136+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.135+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:44:06.141+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:06.187+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.186+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:44:06.222+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:06.222+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:44:06.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.152 seconds
[2023-07-05T13:44:36.394+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:36.396+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:44:36.398+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:36.398+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:36.416+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:36.415+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:44:36.418+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:36.418+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:44:36.420+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:36.420+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:44:36.424+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:44:36.462+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:36.462+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:44:36.491+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:44:36.490+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:44:36.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.131 seconds
[2023-07-05T13:45:06.702+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:06.704+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:45:06.708+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:06.708+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:06.724+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:06.723+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:45:06.726+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:06.726+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:45:06.729+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:06.728+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:45:06.733+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:06.776+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:06.775+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:45:06.815+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:06.815+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:45:06.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.146 seconds
[2023-07-05T13:45:36.919+0000] {processor.py:157} INFO - Started process (PID=107) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:36.921+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:45:36.925+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:36.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:36.947+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:36.946+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:45:36.951+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:36.951+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:45:36.954+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:36.954+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:45:36.958+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:45:37.003+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:37.002+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:45:37.038+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:45:37.037+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:45:37.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.160 seconds
[2023-07-05T13:46:07.139+0000] {processor.py:157} INFO - Started process (PID=126) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:07.141+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:46:07.145+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:07.144+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:07.165+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:07.164+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:46:07.167+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:07.167+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:46:07.169+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:07.169+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:46:07.175+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:07.217+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:07.217+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:46:07.250+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:07.249+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:46:07.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.144 seconds
[2023-07-05T13:46:37.389+0000] {processor.py:157} INFO - Started process (PID=144) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:37.391+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:46:37.394+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:37.394+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:37.413+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:37.411+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:46:37.415+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:37.414+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:46:37.417+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:37.417+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:46:37.421+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:46:37.464+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:37.463+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:46:37.495+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:46:37.494+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:46:37.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.139 seconds
[2023-07-05T13:47:07.606+0000] {processor.py:157} INFO - Started process (PID=161) to work on /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:07.608+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/exercise17.py for tasks to queue
[2023-07-05T13:47:07.612+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:07.611+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:07.629+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:07.628+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/drop_table.sql
[2023-07-05T13:47:07.633+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:07.632+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2023-07-05T13:47:07.638+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:07.637+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/add_data.sql
[2023-07-05T13:47:07.642+0000] {processor.py:836} INFO - DAG(s) dict_keys(['exercise17']) retrieved from /opt/airflow/dags/exercise17.py
[2023-07-05T13:47:07.686+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:07.685+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-07-05T13:47:07.722+0000] {logging_mixin.py:149} INFO - [2023-07-05T13:47:07.722+0000] {dag.py:3490} INFO - Setting next_dagrun for exercise17 to None, run_after=None
[2023-07-05T13:47:07.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/exercise17.py took 0.159 seconds
